name: Deployment

on:
  push:
    branches:
      - canary

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: canary
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Run Build
        run: pnpm generate

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 307ebd51f6c21a90c3873587c11a2913
          projectName: nft-gallery-canary
          directory: dist
          branch: canary
          wranglerVersion: '3'
