name: Playwright Tests
on:
  push:
    branches: [ main, beta, production, nuxt ]
  pull_request:
    branches: [ main, beta, production, nuxt ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Set Enviroment Variable
      env:
        MY_SECRET: ${{ secrets.MNEMONIC_E2E }}
      run: echo "NUXT_APP_MNEMONIC_E2E=${MY_SECRET}" >> .env

    - name: Install dependencies
      uses: ./.github/actions/pnpm-install

    - name: Run Build
      run: pnpm generate
    
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps chromium

    - name: Run Playwright tests
      run: pnpm exec playwright test account.spec.ts
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
